/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "crypt/crypt.h"
#include "constant.h"
/* Header for class security_score_Security */

#ifndef _Included_security_score_Security
#define _Included_security_score_Security
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     security_score_Security
 * Method:    md5
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_security_score_Security_md5
  (JNIEnv *, jclass, jstring);

/*
 * Class:     security_score_Security
 * Method:    verifySign
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_security_score_Security_verifySign
  (JNIEnv *, jclass);

/*
 * Class:     security_score_Security
 * Method:    AESEncrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_security_score_Security_AESEncrypt
  (JNIEnv *, jclass, jstring);

/*
 * Class:     security_score_Security
 * Method:    AESDecrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_security_score_Security_AESDecrypt
  (JNIEnv *, jclass, jstring);

/*
 * Class:     security_score_Security
 * Method:    AESEncryptWithKey
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_security_score_Security_AESEncryptWithKey
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     security_score_Security
 * Method:    AESDecryptWithKey
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_security_score_Security_AESDecryptWithKey
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
